# Expect script for ld-powerpc tests
#   Copyright (C) 2002-2026 Free Software Foundation, Inc.
#
# This file is part of the GNU Binutils.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
# MA 02110-1301, USA.
#

if { ![istarget "powerpc*-*-*"]	} {
    return
}

if {[istarget "*-*-vxworks"]} {
    set ppcvxtests {
	{"VxWorks shared library test 1 (default script)" "-shared" ""
	 "-mregnames" {vxworks1-lib.s}
	 {{readelf --segments vxworks1-lib.sd}}
	 "libvxworks1.so"}
	{"VxWorks shared library test 1"
	 "-shared --hash-style=sysv -Tvxworks1.ld" ""
	 "-mregnames" {vxworks1-lib.s}
         {{readelf {--relocs -T} vxworks1-lib.rd} {objdump -dr vxworks1-lib.dd}
	  {readelf --symbols vxworks1-lib.nd} {readelf -d vxworks1-lib.td}}
	 "libvxworks1.so"}
	{"VxWorks executable test 1 (dynamic)" \
	 "tmpdir/libvxworks1.so -Tvxworks1.ld -q --force-dynamic --hash-style=sysv" ""
	 "-mregnames" {vxworks1.s}
         {{readelf {--relocs -T} vxworks1.rd} {objdump -dr vxworks1.dd}}
	 "vxworks1"}
	{"VxWorks executable test 2 (dynamic)" \
	 "-Tvxworks1.ld -q --force-dynamic --hash-style=sysv" ""
	 "-mregnames" {vxworks2.s}
	 {{readelf --segments vxworks2.sd}}
	 "vxworks2"}
	{"VxWorks executable test 2 (static)"
	 "-Tvxworks1.ld --hash-style=sysv" ""
	 "-mregnames" {vxworks2.s}
	 {{readelf --segments vxworks2-static.sd}}
	 "vxworks2"}
	{"VxWorks relax test"
	 "-Tvxworks1.ld --relax -q --hash-style=sysv" ""
	 "-mregnames" {vxworks-relax.s}
	 {{readelf --relocs vxworks-relax.rd}}
	 "vxworks-relax"}
	{"VxWorks relocatable relax test"
	 "-Tvxworks1.ld -r --relax -q --hash-style=sysv" ""
	 "-mregnames" {vxworks-relax-2.s}
         {{readelf {--relocs -T} vxworks-relax-2.rd}}
	 "vxworks-relax-2"}
    }
    run_ld_link_tests $ppcvxtests
    run_dump_test "vxworks1-static"
    return
}

# powerpc ELF only at the moment.  Disable for nto too, even though it
# is ELF, because we pass -melf32ppc to ld and powerpc-nto-ld wants
# -melf32ppcnto.

if { [is_xcoff_format]
     || [istarget "*-*-pe"] || [istarget "*-*-winnt*"]
     || [istarget "*-*-cygwin*"]
     || [istarget "*-*-lynxos*"]
     || [istarget "*-*-nto*"] } {
    return
}

proc supports_ppc64 { } {
    global ld

    catch "exec $ld --help | grep emulations" tmp
    if [ regexp "elf64l?ppc" $tmp ] then {
	return 1
    } else {
	return 0
    }
}

# List contains test-items with 3 items followed by 2 lists:
# 0:name 1:ld early options 2:ld late options 3:assembler options
# 4:filenames of assembler files 5: action and options. 6: name of output file

# Actions:
# objdump: Apply objdump options on result.  Compare with regex (last arg).
# nm: Apply nm options on result.  Compare with regex (last arg).
# readelf: Apply readelf options on result.  Compare with regex (last arg).

set ppcelftests {
    {"Reloc section order" "-melf32ppc -shared -z nocombreloc -z notext" "" "-a32" {reloc.s}
     {{objdump -hw reloc.d}} "reloc.so"}
    {"APUinfo section processing" "-melf32ppc" ""
     "-a32 -me500" {apuinfo1.s apuinfo-nul.s apuinfo2.s}
     {{readelf -x.PPC.EMB.apuinfo apuinfo.rd}} "apuinfo"}
    {"APUinfo VLE section processing" "-melf32ppc" ""
     "-a32 -me500 -mvle" {apuinfo1.s apuinfo-vle.s apuinfo-vle2.s}
     {{readelf -x.PPC.EMB.apuinfo apuinfo-vle.rd}} "apuinfo-vle"}
    {"APUinfo NULL section processing" "-melf32ppc" ""
     "-a32 -me500" {apuinfo-nul1.s apuinfo-nul.s}
     {{readelf -x.PPC.EMB.apuinfo apuinfo-nul.rd}} "apuinfo"}
    {"TLS32 static exec (markers)" "-melf32ppc" ""
     "-a32 --defsym TLSMARK=1"  {tls32.s tlslib32.s}
     {{objdump -dr tls32.d} {objdump -sj.got tls32.g}
      {objdump -sj.tdata tls32.t}}
     "tls32m"}
    {"TLS32 static exec" "-melf32ppc" "" "-a32"  {tls32.s tlslib32.s}
     {{objdump -dr tls32.d} {objdump -sj.got tls32.g}
      {objdump -sj.tdata tls32.t}}
     "tls32"}
    {"TLS32 static exec (--no-tls-optimize)" "-melf32ppc --no-tls-optimize" ""
     "-a32 --defsym TLSMARK=1"  {tls32.s tlslib32.s}
     {{objdump -dr tls32no.d} {objdump -sj.got tls32no.g}
      {objdump -sj.tdata tls32.t}}
     "tls32no"}
    {"TLS32 helper shared library" "-shared -melf32ppc tmpdir/tlslib32.o" "" "" {}
     {} "libtlslib32.so"}
}

set ppc64elftests {
    {"TLS static exec (markers)" "-melf64ppc --no-plt-align" ""
     "-a64 --defsym TLSMARK=1"  {tls.s tlslib.s}
     {{objdump -dr tls.d} {objdump -sj.got tls.g} {objdump -sj.tdata tls.t}}
     "tlsm"}
}

set ppceabitests {
    {"VLE multiple segments 1" "-melf32ppc -T vle-multiseg-1.ld" ""
     "-a32 -mbig -mregnames -mvle" {vle-multiseg.s}
    {{readelf "-l" vle-multiseg-1.d}} "vle-multiseg-1"}
    {"VLE multiple segments 2" "-melf32ppc -T vle-multiseg-2.ld" ""
     "-a32 -mbig -mregnames -mvle" {vle-multiseg.s}
    {{readelf "-l" vle-multiseg-2.d}} "vle-multiseg-2"}
    {"VLE multiple segments 3" "-melf32ppc -T vle-multiseg-3.ld" ""
     "-a32 -mbig -mregnames -mvle" {vle-multiseg.s}
    {{readelf "-l" vle-multiseg-3.d}} "vle-multiseg-3"}
    {"VLE multiple segments 4" "-melf32ppc -T vle-multiseg-4.ld" ""
     "-a32 -mbig -mregnames -mvle" {vle-multiseg.s}
    {{readelf "-l" vle-multiseg-4.d}} "vle-multiseg-4"}
    {"VLE multiple segments 5" "-melf32ppc -T vle-multiseg-5.ld" ""
     "-a32 -mbig -mregnames -mvle" {vle-multiseg.s}
    {{readelf "-l" vle-multiseg-5.d}} "vle-multiseg-5"}
}

if [istarget "powerpc*le*-*-*"] then {
    set options_regsub(ld) {{-melf([3264]*)ppc} {-melf\1lppc}}

    for {set i 0} {$i < [llength $ppcelftests]} {incr i} {
	set line [lindex $ppcelftests $i]
	set ld_options [lindex $line 1]
	regsub -all elf32ppc $ld_options elf32lppc ld_options
	set line [lreplace $line 1 1 $ld_options]
	set ppcelftests [lreplace $ppcelftests $i $i $line]
    }

    if [ supports_ppc64 ] then {
	for {set i 0} {$i < [llength $ppc64elftests]} {incr i} {
	    set line [lindex $ppc64elftests $i]
	    set ld_options [lindex $line 1]
	    regsub -all elf64ppc $ld_options elf64lppc ld_options
	    set line [lreplace $line 1 1 $ld_options]
	    set ppc64elftests [lreplace $ppc64elftests $i $i $line]
	}
    }
}

run_ld_link_tests $ppcelftests

return

if [ supports_ppc64 ] then {
    run_ld_link_tests $ppc64elftests
    run_dump_test "relbrlt"
    run_dump_test "elfv2so"
    run_dump_test "elfv2exe"
    run_dump_test "elfv2-2so"
    run_dump_test "elfv2-2exe"
    run_dump_test "ambiguousv1"
    run_dump_test "ambiguousv1b"
    run_dump_test "ambiguousv2"
    run_dump_test "ambiguousv2b"
    run_dump_test "defsym"
    run_dump_test "tocvar"
    run_dump_test "tocnovar"
    run_dump_test "tlsldopt"
    run_dump_test "relocsort"
    run_dump_test "addpcis"
    run_dump_test "dotsym1"
    run_dump_test "dotsym2"
    run_dump_test "dotsym3"
    run_dump_test "dotsym4"
    run_dump_test "pr23937"
    run_dump_test "callstub-1"
    run_dump_test "callstub-2"
    run_dump_test "callstub-3"
    run_dump_test "callstub-4"
    run_dump_test "inline-1"
    run_dump_test "inline-2"
    run_dump_test "inline-3"
    run_dump_test "inline-4"
    run_dump_test "inlinepcrel-1"
    run_dump_test "inlinepcrel-2"
    run_dump_test "inlinepcrel-3"
    run_dump_test "tlsgd"
    run_dump_test "tlsld"
    run_dump_test "tlsie"
    run_dump_test "non-contiguous-powerpc64"
    run_dump_test "tprel"
    run_dump_test "pr28827-1"
    run_dump_test "pr28827-2"
}

run_dump_test "localgot"
run_dump_test "tlsldopt32"

run_ld_link_tests $ppceabitests

run_dump_test "plt1"
run_dump_test "sdabase"
run_dump_test "sdabase2"

run_dump_test "attr-gnu-4-00"
run_dump_test "attr-gnu-4-01"
run_dump_test "attr-gnu-4-02"
run_dump_test "attr-gnu-4-03"
run_dump_test "attr-gnu-4-10"
run_dump_test "attr-gnu-4-11"
run_dump_test "attr-gnu-4-12"
run_dump_test "attr-gnu-4-13"
run_dump_test "attr-gnu-4-20"
run_dump_test "attr-gnu-4-21"
run_dump_test "attr-gnu-4-22"
run_dump_test "attr-gnu-4-23"
run_dump_test "attr-gnu-4-31"
run_dump_test "attr-gnu-4-32"
run_dump_test "attr-gnu-4-33"

run_dump_test "attr-gnu-8-11"
run_dump_test "attr-gnu-8-23"
run_dump_test "attr-gnu-8-31"

run_dump_test "attr-gnu-12-11"
run_dump_test "attr-gnu-12-21"

run_dump_test "vle-multiseg-6"

run_dump_test "ppc476-shared"
run_dump_test "ppc476-shared2"

run_dump_test "non-contiguous-powerpc"

run_dump_test "tprel32"
run_dump_test "tprelbad"
run_dump_test tls32ldgd

run_dump_test "undefweak"
