[^:]*: Assembler messages:
[^:]*:5: Error: the specified relocation type is not allowed for MOVK at operand 2 -- `movk x0,#:gotoff_g2:sym'
[^:]*:6: Error: the specified relocation type is not allowed for MOVK at operand 2 -- `movk x0,#:gotoff_g1:sym'
[^:]*:7: Error: the specified relocation type is not allowed for MOVK at operand 2 -- `movk x0,#:gotoff_g0:sym'
[^:]*:8: Error: the specified relocation type is not allowed for 32-bit register at operand 2 -- `movz w0,#:gotoff_g2:sym'
[^:]*:9: Error: the specified relocation type is not allowed for 32-bit register at operand 2 -- `movz w0,#:gotoff_g3:sym'
[^:]*:10: Error: the specified relocation type is not allowed for MOVK at operand 2 -- `movk x0,#:gottprel_g1:sym'
